owner: UmmItC 
repo: Upptime

sites:
  - name: UmmIt
    url: https://ummit.dev
  - name: Storage Server
    url: https://storage.ummit.dev
  - name: InfoSec
    url: https://infosec.ummit.dev
  - name: About
    url: https://about.ummit.dev
  - name: Blog - Main Server
    url: https://blog.ummit.dev
  - name: Blog - Codeberg Page
    url: https://cb-blog.ummit.dev
  - name: Blog - Cloudflare Page
    url: https://cf-blog.ummit.dev
  - name: Blog - Gitlab page
    url: https://gl-blog.ummit.dev
  - name: Blog - Github page
    url: https://gh-blog.ummit.dev

status-website:
  cname: status.ummit.dev
  # baseUrl: /Upptime
  logoUrl: https://avatars.githubusercontent.com/u/128139875?v=4
  name: UmmIt - Status page
  introTitle: "**UmmIt Status** ALL Server Status."
  introMessage: I Love Open-source.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  favicon: https://avatars.githubusercontent.com/u/128139875?v=4
